print ("True and True",",",True and True)
print ("False and True",",",False and True)
print ("1 == 1 and 2 == 1",",",1 == 1 and 2 == 1)
print ("test == test",",","test" == "test")
print ("1 == 1 and 2 != 1",",",1 == 1 and 2 != 1)
print ("True and 1 == 1",",",True and 1 == 1)
print ("False and 0 != 0",",",False and 0 != 0)
print ("True or 1 == 1",",",True or 1 == 1)
print ("test == testing",",","test" == "testing")
print ("1 != 0 and 2 == 1",",",1 != 0 and 2 == 1)
print ("test != testing",",","test" != "testing")
print ("test == 1",",","test" == 1)
print ("not (True and False)",",",not (True and False))
print ("not (1 == 1 and 0 != 1)",",",not (1 == 1 and 0 != 1))
print ("not (10 == 1 or 1000 == 1000)",",",not (10 == 1 or 1000 == 1000))
print ("not (1 != 10 or 3 == 4)",",",not (1 != 10 or 3 == 4))
print ("not (test != testing and Zed == Cool Guy)",",",not ("test" != "testing" and "Zed" == "Cool Guy"))
print ("1 == 1 and not (test == 1 or 1 == 0)",",",1 == 1 and not ("test" == 1 or 1 == 0))
print ("chunky == bacon and not (3 == 4 or 3==3)",",","chunky" == "bacon" and not (3 == 4 or 3==3))
print ("3 == 3 and not (testing == testing or Python == Fun)",",",3 == 3 and not ("testing" == "testing" or "Python" == "Fun"))
